version: '3.7'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'vehicles_hiring'


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
  

